# This file is only meant to override image definitions and pull the image from GHCR; the full service definitions are in compose.yaml.
# The fully merged configuration can be viewed with:
# docker compose -f compose.yaml -f compose.prerelease.yaml config

# Command examples:
# COMPOSE_FILE=compose.yaml:compose.prerelease.yaml docker compose up -d
# docker compose --profile indexer up -d
# docker compose run --rm influence-eventauditor

x-image: &image
  image: ghcr.io/adaliafoundation/influence-server:prerelease
  environment:
    NODE_ENV: prerelease

services:
  influence-server:
    <<: *image
    command: ["npm", "run", "start"]

  influence-indexer:
    <<: *image

  influence-ethereumeventretriever:
    <<: *image

  influence-starkneteventretriever:
    <<: *image

  influence-eventprocessor:
    <<: *image

  influence-eventauditor:
    <<: *image

  influence-agreementauditor:
    <<: *image

  influence-tools:
    <<: *image
